import { auth } from '@clerk/nextjs/server';
import { redirect } from 'next/navigation';
import { Megaphone } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';
import { AdCenterClient } from './AdCenterClient';
import type { Profile } from '@/types';

export const metadata = { title: 'Ad Center — Orignest' };

export default async function AdCenterPage() {
  const { userId, orgId } = await auth();
  if (!userId || !orgId) redirect('/sign-in');

  const sb = createClient();

  const [{ data: org }, { data: landingPages }, { data: profiles }] = await Promise.all([
    sb.from('organizations').select('id, name').eq('clerk_org_id', orgId).maybeSingle(),
    sb.from('landing_pages').select('id, slug, headline, active, page_views, leads_captured, created_at').order('created_at', { ascending: false }),
    sb.from('profiles').select('id, first_name, last_name, nmls_id, email, phone').eq('active', true).order('first_name'),
  ]);

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Page header */}
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-2.5 mb-1">
            <div className="w-9 h-9 rounded-xl bg-[#007AFF]/15 flex items-center justify-center">
              <Megaphone size={18} className="text-[#007AFF]" />
            </div>
            <h1 className="text-[22px] font-bold text-[#1C1C1E] tracking-tight">Ad Center</h1>
          </div>
          <p className="text-[14px] text-[#8A8A8E] ml-11">
            Create mortgage ad campaigns, manage creative assets, and build LO landing pages.
          </p>
        </div>
      </div>

      {/* Stats row */}
      <div className="grid grid-cols-4 gap-3">
        {[
          { label: 'Active Campaigns', value: '—', sub: 'No active campaigns' },
          { label: 'Leads This Month', value: '—', sub: 'From all campaigns' },
          { label: 'Landing Pages', value: String(landingPages?.length ?? 0), sub: 'Total published' },
          { label: 'Avg. Cost per Lead', value: '—', sub: 'Across all platforms' },
        ].map(stat => (
          <div key={stat.label} className="bg-white border border-black/[0.06] shadow-sm rounded-2xl px-4 py-3.5">
            <p className="text-[11px] font-semibold text-[#8A8A8E] uppercase tracking-wide mb-1">{stat.label}</p>
            <p className="text-[22px] font-bold text-[#1C1C1E] leading-none">{stat.value}</p>
            <p className="text-[11px] text-[#C7C7CC] mt-0.5">{stat.sub}</p>
          </div>
        ))}
      </div>

      {/* Main content */}
      <div className="bg-white border border-black/[0.06] shadow-sm rounded-2xl p-6">
        <AdCenterClient
          landingPages={landingPages ?? []}
          profiles={(profiles ?? []) as Profile[]}
          orgSlug={org?.name?.toLowerCase().replace(/\s+/g, '-') ?? 'org'}
        />
      </div>

      {/* Compliance footer */}
      <p className="text-[11px] text-[#C7C7CC] text-center pb-2">
        All ad copy generated by Orignest AI must be reviewed for compliance before publishing.
        Not a commitment to lend. Subject to credit approval. Equal Housing Lender.
      </p>
    </div>
  );
}
