// Sample lender data — displayed until org adds their own AE relationships
// NOT stored in the database — used as reference/demo data only

export interface SeedLender {
  id: string;
  name: string;
  channel: 'wholesale' | 'correspondent' | 'direct' | 'hard_money' | 'private';
  website: string;
  products: string[];
  licensed_states: string[];
  min_fico: number;
  max_ltv: number;
  specialty_tags: string[];
  avg_turnaround_days: number;
  is_preferred: boolean;
  notes: string;
  loans_submitted: number;
  loans_closed: number;
  avg_days_to_close: number;
  ae_name: string;
  ae_phone: string;
  ae_email: string;
  product_matrix: Array<{
    loan_type: string;
    min_fico: number;
    max_ltv: number;
    max_dti: number;
    max_loan_amount: number;
    overlay_notes: string;
  }>;
}

export const SEED_LENDERS: SeedLender[] = [
  {
    id: 'seed-001',
    name: 'Summit Wholesale Lending',
    channel: 'wholesale',
    website: 'https://example.com',
    products: ['Conventional', 'FHA', 'VA', 'USDA', 'Jumbo'],
    licensed_states: ['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'],
    min_fico: 620,
    max_ltv: 97.0,
    specialty_tags: [],
    avg_turnaround_days: 18,
    is_preferred: true,
    notes: 'Reliable agency lender. Fast on conventional, slightly slower on FHA. Great AE support.',
    loans_submitted: 47,
    loans_closed: 38,
    avg_days_to_close: 21,
    ae_name: 'Marcus Delgado',
    ae_phone: '(404) 555-0121',
    ae_email: 'mdelgado@summitws.example.com',
    product_matrix: [
      { loan_type: 'Conventional', min_fico: 620, max_ltv: 97.0, max_dti: 50, max_loan_amount: 766550, overlay_notes: 'DU approve/eligible required. 2yr employment history.' },
      { loan_type: 'FHA', min_fico: 580, max_ltv: 96.5, max_dti: 57, max_loan_amount: 498257, overlay_notes: 'Manual underwrites to 580 FICO with compensating factors.' },
      { loan_type: 'VA', min_fico: 580, max_ltv: 100, max_dti: 60, max_loan_amount: 1500000, overlay_notes: 'No county loan limits for VA. COE required at submission.' },
      { loan_type: 'USDA', min_fico: 640, max_ltv: 100, max_dti: 46, max_loan_amount: 400000, overlay_notes: 'GUS approval required. Income eligibility per county AMI.' },
      { loan_type: 'Jumbo', min_fico: 700, max_ltv: 89.99, max_dti: 43, max_loan_amount: 3000000, overlay_notes: '12mo reserves required. Full doc only. Two appraisals >$1.5M.' },
    ],
  },
  {
    id: 'seed-002',
    name: 'Pacific Non-QM Partners',
    channel: 'wholesale',
    website: 'https://example.com',
    products: ['Non-QM', 'DSCR', 'Bank Statement', 'ITIN', 'Foreign National'],
    licensed_states: ['CA','TX','FL','NY','NV','AZ','CO','WA','OR','GA','NC','VA','MD','IL','NJ'],
    min_fico: 580,
    max_ltv: 80.0,
    specialty_tags: ['Non-QM specialist', 'DSCR specialist', 'Foreign national', 'ITIN', 'Self-employed'],
    avg_turnaround_days: 14,
    is_preferred: true,
    notes: 'Best Non-QM pricing in the market. Strong on DSCR and bank statement. No W2 borrowers.',
    loans_submitted: 29,
    loans_closed: 22,
    avg_days_to_close: 19,
    ae_name: 'Keiko Watanabe',
    ae_phone: '(310) 555-0188',
    ae_email: 'kwatanabe@pacificnonqm.example.com',
    product_matrix: [
      { loan_type: 'Bank Statement', min_fico: 620, max_ltv: 80.0, max_dti: 55, max_loan_amount: 3000000, overlay_notes: '12 or 24mo bank statements. Personal or business. 50% expense factor on business.' },
      { loan_type: 'DSCR', min_fico: 620, max_ltv: 80.0, max_dti: 0, max_loan_amount: 5000000, overlay_notes: 'Min DSCR 1.0x. No income docs required. Rate add-on below 1.25x DSCR.' },
      { loan_type: 'Non-QM', min_fico: 580, max_ltv: 75.0, max_dti: 55, max_loan_amount: 2000000, overlay_notes: 'Recent credit events OK with 20% down. LOX required.' },
      { loan_type: 'ITIN', min_fico: 600, max_ltv: 75.0, max_dti: 50, max_loan_amount: 1000000, overlay_notes: 'Valid ITIN required. 2yr tax history. No SSN required.' },
      { loan_type: 'Foreign National', min_fico: 0, max_ltv: 65.0, max_dti: 0, max_loan_amount: 5000000, overlay_notes: 'No US credit required. Passport + asset verification. Reserve requirements apply.' },
    ],
  },
  {
    id: 'seed-003',
    name: 'Meridian FHA-VA Specialists',
    channel: 'wholesale',
    website: 'https://example.com',
    products: ['FHA', 'VA', 'USDA', 'Conventional'],
    licensed_states: ['TX','FL','GA','NC','SC','TN','AL','MS','LA','AR','OK','KY','VA','MD','DC'],
    min_fico: 500,
    max_ltv: 100.0,
    specialty_tags: ['Recent credit events'],
    avg_turnaround_days: 21,
    is_preferred: false,
    notes: 'Excellent on manual underwrites. Will go to 500 FICO on FHA with strong compensating factors. VA expert.',
    loans_submitted: 18,
    loans_closed: 14,
    avg_days_to_close: 28,
    ae_name: 'Darnell Thompson',
    ae_phone: '(713) 555-0244',
    ae_email: 'dthompson@meridianfhava.example.com',
    product_matrix: [
      { loan_type: 'FHA', min_fico: 500, max_ltv: 96.5, max_dti: 57, max_loan_amount: 498257, overlay_notes: '500-579 FICO: 10% down required. Manual UW available to 57% DTI with compensating factors.' },
      { loan_type: 'VA', min_fico: 500, max_ltv: 100, max_dti: 65, max_loan_amount: 2000000, overlay_notes: 'Manual UW available. Residual income analysis required per VA guidelines.' },
      { loan_type: 'USDA', min_fico: 580, max_ltv: 100, max_dti: 50, max_loan_amount: 350000, overlay_notes: 'Rural eligible areas only. Income limits apply. GRH and direct programs.' },
      { loan_type: 'Conventional', min_fico: 620, max_ltv: 95.0, max_dti: 45, max_loan_amount: 766550, overlay_notes: 'LP eligible required for >95% LTV.' },
    ],
  },
  {
    id: 'seed-004',
    name: 'Apex Jumbo & Luxury',
    channel: 'correspondent',
    website: 'https://example.com',
    products: ['Jumbo', 'Super Jumbo', 'Non-QM'],
    licensed_states: ['CA','NY','FL','TX','WA','CO','MA','CT','NJ','IL','GA','VA','MD','DC','HI'],
    min_fico: 700,
    max_ltv: 80.0,
    specialty_tags: ['Self-employed'],
    avg_turnaround_days: 25,
    is_preferred: false,
    notes: 'Best jumbo rates for 760+ FICO borrowers. Slow UW but very competitive pricing on $2M+.',
    loans_submitted: 8,
    loans_closed: 6,
    avg_days_to_close: 32,
    ae_name: 'Priya Nair',
    ae_phone: '(213) 555-0167',
    ae_email: 'pnair@apexjumbo.example.com',
    product_matrix: [
      { loan_type: 'Jumbo', min_fico: 700, max_ltv: 80.0, max_dti: 43, max_loan_amount: 5000000, overlay_notes: '24mo self-employed history if applicable. Full doc only. VOE required.' },
      { loan_type: 'Super Jumbo', min_fico: 740, max_ltv: 70.0, max_dti: 40, max_loan_amount: 20000000, overlay_notes: '>$5M requires additional approval. Two full appraisals. Asset depletion OK.' },
      { loan_type: 'Non-QM', min_fico: 700, max_ltv: 75.0, max_dti: 55, max_loan_amount: 4000000, overlay_notes: 'Asset depletion and bank statement options for HNW self-employed.' },
    ],
  },
  {
    id: 'seed-005',
    name: 'Atlas Bridge Capital',
    channel: 'hard_money',
    website: 'https://example.com',
    products: ['Bridge', 'Fix & Flip', 'Construction', 'DSCR'],
    licensed_states: ['CA','TX','FL','GA','CO','AZ','NV','WA','OR','NC','SC','TN','OH','PA','NY'],
    min_fico: 580,
    max_ltv: 75.0,
    specialty_tags: ['DSCR specialist', 'Recent credit events'],
    avg_turnaround_days: 7,
    is_preferred: false,
    notes: 'Fast close on bridge — 7-10 days. High rates but reliable. Good for investor clients needing speed.',
    loans_submitted: 11,
    loans_closed: 9,
    avg_days_to_close: 9,
    ae_name: 'Cody Briggs',
    ae_phone: '(678) 555-0339',
    ae_email: 'cbriggs@atlasbridgecap.example.com',
    product_matrix: [
      { loan_type: 'Bridge', min_fico: 580, max_ltv: 75.0, max_dti: 0, max_loan_amount: 5000000, overlay_notes: 'Asset-based lending. No income required. Exit strategy required at submission.' },
      { loan_type: 'Fix & Flip', min_fico: 580, max_ltv: 75.0, max_dti: 0, max_loan_amount: 2000000, overlay_notes: 'ARV up to 70%. Draw schedule for rehab funds. Experienced investors preferred.' },
      { loan_type: 'Construction', min_fico: 620, max_ltv: 75.0, max_dti: 0, max_loan_amount: 3000000, overlay_notes: 'Ground-up or major rehab. Interest reserve built in. Inspections required per draw.' },
      { loan_type: 'DSCR', min_fico: 580, max_ltv: 75.0, max_dti: 0, max_loan_amount: 3000000, overlay_notes: 'Min DSCR 1.0x. Short-term bridge to permanent DSCR available.' },
    ],
  },
  {
    id: 'seed-006',
    name: 'Cornerstone Commercial Finance',
    channel: 'direct',
    website: 'https://example.com',
    products: ['Commercial', 'SBA 7(a)', 'SBA 504', 'DSCR', 'Mixed-Use'],
    licensed_states: ['TX','CA','FL','NY','IL','GA','NC','VA','OH','PA','AZ','CO','WA','MA','NJ'],
    min_fico: 650,
    max_ltv: 80.0,
    specialty_tags: ['DSCR specialist'],
    avg_turnaround_days: 30,
    is_preferred: false,
    notes: 'Strong SBA preferred lender. Turnaround is slow but approval rates are high on SBA 7a.',
    loans_submitted: 6,
    loans_closed: 4,
    avg_days_to_close: 45,
    ae_name: 'Sandra Kim',
    ae_phone: '(972) 555-0412',
    ae_email: 'skim@cornerstonecommercial.example.com',
    product_matrix: [
      { loan_type: 'Commercial', min_fico: 650, max_ltv: 75.0, max_dti: 0, max_loan_amount: 25000000, overlay_notes: 'Global cash flow underwriting. 3yr business tax returns required.' },
      { loan_type: 'SBA 7(a)', min_fico: 650, max_ltv: 90.0, max_dti: 0, max_loan_amount: 5000000, overlay_notes: 'Preferred SBA lender — faster approval. 2yr in business minimum. Personal guarantee required.' },
      { loan_type: 'SBA 504', min_fico: 650, max_ltv: 90.0, max_dti: 0, max_loan_amount: 14000000, overlay_notes: 'Owner-occupied only. Certified Development Company required. Job creation metrics apply.' },
      { loan_type: 'Mixed-Use', min_fico: 660, max_ltv: 75.0, max_dti: 0, max_loan_amount: 8000000, overlay_notes: 'Min 51% commercial component. Market rents used for residential units.' },
    ],
  },
  {
    id: 'seed-007',
    name: 'Liberty Correspondent Lending',
    channel: 'correspondent',
    website: 'https://example.com',
    products: ['Conventional', 'FHA', 'VA', 'Non-QM', 'Jumbo'],
    licensed_states: ['FL','GA','NC','SC','TN','AL','MS','LA','TX','OK','AR','KY','VA','MD','DC','WV','OH','IN','KS','MO'],
    min_fico: 600,
    max_ltv: 97.0,
    specialty_tags: ['Self-employed', 'Recent credit events'],
    avg_turnaround_days: 22,
    is_preferred: false,
    notes: 'Good fallback lender for non-delegated correspondent. Competitive on FHA overlays.',
    loans_submitted: 14,
    loans_closed: 10,
    avg_days_to_close: 26,
    ae_name: 'Robert Castillo',
    ae_phone: '(904) 555-0571',
    ae_email: 'rcastillo@libertycorr.example.com',
    product_matrix: [
      { loan_type: 'Conventional', min_fico: 620, max_ltv: 97.0, max_dti: 50, max_loan_amount: 766550, overlay_notes: 'Non-delegated UW. Full DU/LP review required.' },
      { loan_type: 'FHA', min_fico: 600, max_ltv: 96.5, max_dti: 55, max_loan_amount: 498257, overlay_notes: 'Minimum 600 overlay. Non-delegated UW. Fast turn times on FHA.' },
      { loan_type: 'VA', min_fico: 580, max_ltv: 100, max_dti: 60, max_loan_amount: 1500000, overlay_notes: 'SAR on staff — fast VA LAPP review.' },
      { loan_type: 'Jumbo', min_fico: 680, max_ltv: 85.0, max_dti: 43, max_loan_amount: 2000000, overlay_notes: '6mo reserves required. Two years W2 or self-employed.' },
    ],
  },
  {
    id: 'seed-008',
    name: 'Ridgeline DSCR & Investor',
    channel: 'wholesale',
    website: 'https://example.com',
    products: ['DSCR', 'Non-QM', 'Bank Statement', 'Bridge', 'Short-Term Rental'],
    licensed_states: ['FL','TX','GA','NC','SC','TN','CO','AZ','NV','CA','WA','OR','OH','IN','MI','WI','MN'],
    min_fico: 620,
    max_ltv: 80.0,
    specialty_tags: ['DSCR specialist', 'Self-employed', 'Recent credit events'],
    avg_turnaround_days: 12,
    is_preferred: true,
    notes: 'Best DSCR product in the market. Allows short-term rental (Airbnb/VRBO) income. Fast pricing.',
    loans_submitted: 33,
    loans_closed: 26,
    avg_days_to_close: 17,
    ae_name: 'Jessica Monroe',
    ae_phone: '(561) 555-0688',
    ae_email: 'jmonroe@ridgelinedscr.example.com',
    product_matrix: [
      { loan_type: 'DSCR', min_fico: 620, max_ltv: 80.0, max_dti: 0, max_loan_amount: 5000000, overlay_notes: 'Min DSCR 0.75x with rate add-on. STR income accepted using AirDNA market rent. 1-8 units.' },
      { loan_type: 'Bank Statement', min_fico: 640, max_ltv: 80.0, max_dti: 55, max_loan_amount: 3000000, overlay_notes: '12mo personal or 24mo business. CPA letter accepted in lieu of business statements.' },
      { loan_type: 'Non-QM', min_fico: 620, max_ltv: 80.0, max_dti: 55, max_loan_amount: 3000000, overlay_notes: 'P&L prepared by CPA accepted. 2yr seasoning on BK/FC.' },
      { loan_type: 'Short-Term Rental', min_fico: 640, max_ltv: 75.0, max_dti: 0, max_loan_amount: 3000000, overlay_notes: 'AirDNA underwriting. Market rent or actual Airbnb/VRBO income. 1-4 units only.' },
    ],
  },
  {
    id: 'seed-009',
    name: 'Keystone Agency Partners',
    channel: 'wholesale',
    website: 'https://example.com',
    products: ['Conventional', 'HomeReady', 'HomePossible', 'FHA', 'VA'],
    licensed_states: ['PA','NJ','NY','CT','MA','RI','DE','MD','DC','OH','WV','VA','NC'],
    min_fico: 620,
    max_ltv: 97.0,
    specialty_tags: [],
    avg_turnaround_days: 16,
    is_preferred: false,
    notes: 'Strong on HomeReady/HomePossible. First-time buyer specialist. Good AMI limit knowledge.',
    loans_submitted: 21,
    loans_closed: 17,
    avg_days_to_close: 20,
    ae_name: 'Theresa Walsh',
    ae_phone: '(215) 555-0743',
    ae_email: 'twalsh@keystoneagency.example.com',
    product_matrix: [
      { loan_type: 'Conventional', min_fico: 620, max_ltv: 97.0, max_dti: 50, max_loan_amount: 766550, overlay_notes: 'DU required. HomeReady/HomePossible available.' },
      { loan_type: 'HomeReady', min_fico: 620, max_ltv: 97.0, max_dti: 50, max_loan_amount: 766550, overlay_notes: 'Income at or below 80% AMI. Homebuyer education required. Reduced MI.' },
      { loan_type: 'FHA', min_fico: 620, max_ltv: 96.5, max_dti: 55, max_loan_amount: 498257, overlay_notes: '620 FICO overlay. No manual UW.' },
      { loan_type: 'VA', min_fico: 600, max_ltv: 100, max_dti: 60, max_loan_amount: 1500000, overlay_notes: 'Competitive VA pricing. Fast COE processing.' },
    ],
  },
  {
    id: 'seed-010',
    name: 'Thornwood Private Capital',
    channel: 'private',
    website: 'https://example.com',
    products: ['Bridge', 'Construction', 'Commercial', 'Land', 'Fix & Flip'],
    licensed_states: ['CA','TX','FL','NY','NJ','CT','GA','NC','CO','WA','AZ','NV'],
    min_fico: 0,
    max_ltv: 65.0,
    specialty_tags: ['Non-QM specialist', 'Recent credit events', 'Foreign national'],
    avg_turnaround_days: 5,
    is_preferred: false,
    notes: 'True private money — no FICO requirement. Asset-based only. Rates are high. Use for time-sensitive deals.',
    loans_submitted: 4,
    loans_closed: 4,
    avg_days_to_close: 7,
    ae_name: 'Hunter Blackwood',
    ae_phone: '(917) 555-0892',
    ae_email: 'hblackwood@thornwoodprivate.example.com',
    product_matrix: [
      { loan_type: 'Bridge', min_fico: 0, max_ltv: 65.0, max_dti: 0, max_loan_amount: 10000000, overlay_notes: 'No credit minimum. Equity and exit strategy only. 1-24 month terms.' },
      { loan_type: 'Construction', min_fico: 0, max_ltv: 65.0, max_dti: 0, max_loan_amount: 8000000, overlay_notes: 'Ground-up. No presale requirement. Experience preferred.' },
      { loan_type: 'Land', min_fico: 0, max_ltv: 50.0, max_dti: 0, max_loan_amount: 5000000, overlay_notes: 'Raw land to 50% LTV. Entitled land preferred. Environmental review may be required.' },
    ],
  },
];
