/**
 * Phase 4.5 — "What happens next" plain-English card (server-only).
 *
 * Returns a warm, jargon-free explanation of the borrower's current loan stage,
 * generated by Claude Haiku and cached on the lead (regenerated only when the
 * stage changes). Falls back to the provided static text if generation fails.
 */
import 'server-only';
import Anthropic from '@anthropic-ai/sdk';
import { createAdminClient } from '@/lib/supabase/admin';

const MODEL = 'claude-haiku-4-5';

export async function getOrGenerateNextStep(params: {
  leadId: string;
  orgId: string;
  stage: string;
  stageLabel: string;
  openConditions: number;
  fallback: string;
}): Promise<string> {
  const { leadId, orgId, stage, stageLabel, openConditions, fallback } = params;
  const sb = createAdminClient();

  const { data: lead } = await sb
    .from('leads')
    .select('next_step_ai, next_step_ai_stage')
    .eq('id', leadId)
    .eq('org_id', orgId)
    .maybeSingle();

  // Cache hit: same stage already explained.
  if (lead?.next_step_ai && lead.next_step_ai_stage === stage) {
    return lead.next_step_ai as string;
  }

  try {
    const client = new Anthropic();
    const message = await client.messages.create({
      model: MODEL,
      max_tokens: 220,
      system:
        'You explain a mortgage process step to a first-time homebuyer. Write 2–3 short sentences in plain, warm English. Speak directly to "you". No jargon, no technical terms, no markdown. Cover: what is happening now, what (if anything) they need to do, and what to expect next.',
      messages: [
        {
          role: 'user',
          content: `Current stage: ${stageLabel}\nOutstanding items needed from the borrower: ${openConditions}\n\nWrite the explanation.`,
        },
      ],
    });

    const text = message.content[0]?.type === 'text' ? message.content[0].text.trim() : '';
    if (!text) return fallback;

    await sb
      .from('leads')
      .update({ next_step_ai: text, next_step_ai_stage: stage })
      .eq('id', leadId)
      .eq('org_id', orgId);

    return text;
  } catch {
    return fallback;
  }
}
